# Generated by Django 3.1.4 on 2020-12-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Echo',
        ),
    ]
