# Generated by Django 3.1.3 on 2021-01-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseHours', models.TextField(max_length=100)),
                ('CourseName', models.TextField(max_length=100)),
                ('CalenderRefrence', models.TextField(max_length=100)),
                ('AcademicCredit', models.IntegerField()),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'COURSE',
            },
        ),
    ]
