# Generated by Django 3.1.3 on 2021-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuWeight',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Category', models.TextField(max_length=100)),
                ('AU', models.IntegerField()),
            ],
            options={
                'db_table': 'AU_WEIGHT',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CategoryType', models.TextField(max_length=100)),
                ('Element', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'CONTENT_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FName', models.TextField(max_length=100)),
                ('LName', models.TextField(max_length=100)),
                ('Phone', models.TextField(max_length=100)),
                ('Office', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'COORDINATOR',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CourseHours', models.TextField(max_length=100)),
                ('CourseName', models.TextField(max_length=100)),
                ('CalenderRefrence', models.TextField(max_length=100)),
                ('AcademicCredit', models.IntegerField()),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'COURSE',
            },
        ),
        migrations.CreateModel(
            name='GradeDetermination',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Component', models.TextField(max_length=100)),
                ('OutcomeEvaluated', models.TextField(max_length=100)),
                ('Weight', models.IntegerField()),
            ],
            options={
                'db_table': 'GRADE_DETERMINATION',
            },
        ),
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('LowerLimit', models.IntegerField()),
                ('UpperLimit', models.IntegerField()),
                ('LetterGrade', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'GRADE_DISTRIBUTION',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('GradeNotes', models.TextField(max_length=500)),
                ('Examination', models.TextField(max_length=500)),
                ('CourseDescription', models.TextField(max_length=500)),
                ('UseCalc', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'INFO',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('LabNum', models.TextField(max_length=500)),
                ('NumberOfLabs', models.IntegerField()),
                ('LabType', models.TextField(max_length=500)),
                ('SafetyExamined', models.TextField(max_length=100)),
                ('SafetyTaught', models.TextField(max_length=100)),
                ('FName', models.TextField(max_length=100)),
                ('LName', models.TextField(max_length=100)),
                ('Phone', models.TextField(max_length=100)),
                ('Office', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'LAB',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('LectureNum', models.TextField(max_length=100)),
                ('FName', models.TextField(max_length=100)),
                ('LName', models.TextField(max_length=100)),
                ('Phone', models.TextField(max_length=100)),
                ('Office', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'LECTURE',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('OutcomeNum', models.IntegerField()),
                ('Description', models.TextField(max_length=500)),
                ('GraduateAttribute', models.TextField(max_length=500)),
                ('InstructionLvl', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'OUTCOME',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('SectionNumber', models.TextField(max_length=100)),
                ('Students', models.IntegerField()),
                ('Hours', models.IntegerField()),
            ],
            options={
                'db_table': 'SECTION',
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TITLE', models.TextField(max_length=200)),
                ('Publisher', models.TextField(max_length=200)),
                ('Author', models.TextField(max_length=200)),
                ('Edition', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'TEXTBOOK',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('SectionNum', models.TextField(max_length=100)),
                ('Days', models.TextField(max_length=100)),
                ('Time', models.TextField(max_length=100)),
                ('Location', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'TIMETABLE',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('CourseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TutorialNum', models.TextField(max_length=100)),
                ('FName', models.TextField(max_length=100)),
                ('LName', models.TextField(max_length=100)),
                ('Phone', models.TextField(max_length=100)),
                ('Office', models.TextField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'TUTORIAL',
            },
        ),
    ]
