# Generated by Django 3.1.3 on 2021-01-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auweight',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gradedetermination',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='outcome',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='textbook',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='CourseID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
