# Generated by Django 3.1.3 on 2021-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseoutline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Examination',
            field=models.TextField(max_length=5000),
        ),
    ]
