# Generated by Django 3.1.4 on 2020-12-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='echo',
            new_name='echos',
        ),
    ]
