# Generated by Django 3.1.4 on 2020-12-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_auto_20201210_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echos',
            old_name='alias',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='echos',
            name='name',
        ),
    ]
