DROP schema if exists COURSE_OUTLINE;
CREATE schema COURSE_OUTLINE;
 use COURSE_OUTLINE;
 DROP TABLE if Exists COURSE;
CREATE TABLE COURSE (
  `CourseID` VARCHAR(45) NOT NULL,
  `CourseHours` VARCHAR(100) NULL,
  `CourseName` VARCHAR(200) NULL,
  `CalenderRefrence` VARCHAR(200) NULL,
  `AcademicCredit` INT NULL,
  `DateCreated` DATETIME NULL,
  PRIMARY KEY (`CourseID`));
 DROP TABLE if Exists INFO;
CREATE TABLE `COURSE_OUTLINE`.`INFO` (
  `CourseID` VARCHAR(45) NOT NULL,
  `GradeNotes` MEDIUMTEXT NULL,
  `Examination` MEDIUMTEXT NULL,
  `CourseDescription` MEDIUMTEXT NULL,
  `UseCalc` VARCHAR(100) NULL,
  PRIMARY KEY (`CourseID`),
  CONSTRAINT `CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON UPDATE CASCADE);
 DROP TABLE if Exists TEXTBOOK;
CREATE TABLE `COURSE_OUTLINE`.`TEXTBOOK` (
  `CourseID` VARCHAR(45) NOT NULL,
  `TITLE` VARCHAR(200) NOT NULL,
  `Publisher` VARCHAR(200) NULL,
  `Author` VARCHAR(200) NULL,
  `Edition` VARCHAR(200) NULL,
  PRIMARY KEY (`CourseID`, `TITLE`),
  CONSTRAINT `TEXTBOOK_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
 DROP TABLE if Exists COORDINATOR;
    CREATE TABLE `COURSE_OUTLINE`.`COORDINATOR` (
  `CourseID` VARCHAR(45) NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Phone` VARCHAR(10) NULL,
  `Office` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CourseID`),
  CONSTRAINT `COORDINATOR_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
  
   DROP TABLE if Exists GRADE_DISTRIBUTION;
    CREATE TABLE `COURSE_OUTLINE`.`GRADE_DISTRIBUTION` (
  `CourseID` VARCHAR(45) NOT NULL,
  `LowerLimit` INT NULL,
  `UpperLimit` INT NULL,
  `LetterGrade` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`CourseID`, `LetterGrade`),
  CONSTRAINT `GRADE_DISTRIBUTION_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
     DROP TABLE if Exists GRADE_DETERMINATION;
    CREATE TABLE `COURSE_OUTLINE`.`GRADE_DETERMINATION` (
  `CourseID` VARCHAR(45) NOT NULL,
  `Component` VARCHAR(45) NOT NULL,
  `OutcomeEvaluated` VARCHAR(45) NULL,
  `Weight` INT NULL,
  PRIMARY KEY (`CourseID`, `Component`),
  CONSTRAINT `GRADE_DETERMINATION_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
DROP TABLE if Exists OUTCOME;
CREATE TABLE `COURSE_OUTLINE`.`OUTCOME` (
  `CourseID` VARCHAR(45) NOT NULL,
  `OutcomeNum` INT NOT NULL,
  `Description` MEDIUMTEXT NULL,
  `GraduateAttribute` VARCHAR(45) NULL,
  `InstructionLvl` VARCHAR(45) NULL,
  PRIMARY KEY (`CourseID`, `OutcomeNum`),
  CONSTRAINT `OUTCOME_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);

DROP TABLE if Exists CONTENT_CATEGORY;

CREATE TABLE `COURSE_OUTLINE`.`CONTENT_CATEGORY` (
  `CourseID` VARCHAR(45) NOT NULL,
  `CategoryType` VARCHAR(45) NOT NULL,
  `Element` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CourseID`, `CategoryType`,`Element` ),
  CONSTRAINT `CONTENT_CATEGORY_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
DROP TABLE if Exists AU_WEIGHT;
    CREATE TABLE `COURSE_OUTLINE`.`AU_WEIGHT` (
  `CourseID` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `AU%` INT NULL,
  PRIMARY KEY (`CourseID`, `Category`),
  CONSTRAINT `AU_WEIGHT_CourseID`
    FOREIGN KEY (`CourseID` , `Category`)
    REFERENCES `COURSE_OUTLINE`.`CONTENT_CATEGORY` (`CourseID` , `CategoryType`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
DROP TABLE if Exists SECTION;
CREATE TABLE `COURSE_OUTLINE`.`SECTION` (
  `CourseID` VARCHAR(45) NOT NULL,
  `SectionNumber` VARCHAR(4) NOT NULL,
  `Students` INT NULL,
  `Hours` INT NULL,
  PRIMARY KEY (`CourseID`, `SectionNumber`),
  CONSTRAINT `Section_CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `COURSE_OUTLINE`.`COURSE` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
DROP TABLE if Exists LECTURE;
CREATE TABLE `COURSE_OUTLINE`.`LECTURE` (
  `CourseID` VARCHAR(45) NOT NULL,
  `LectureNum` VARCHAR(4) NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Office` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CourseID`, `LectureNum`),
  CONSTRAINT `Lecture`
    FOREIGN KEY (`CourseID` , `LectureNum`)
    REFERENCES `COURSE_OUTLINE`.`SECTION` (`CourseID` , `SectionNumber`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
    DROP TABLE if Exists LAB;
    CREATE TABLE `COURSE_OUTLINE`.`LAB` (
  `CourseID` VARCHAR(45) NOT NULL,
  `LabNum` VARCHAR(4) NOT NULL,
  `NumberOfLabs` INT NULL,
  `LabType` VARCHAR(45) NULL,
  `SafetyExamined` VARCHAR(45) NULL,
  `SafetyTaught` VARCHAR(45) NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Office` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CourseID`, `LabNum`),
  CONSTRAINT `LAB`
    FOREIGN KEY (`CourseID` , `LabNum`)
    REFERENCES `COURSE_OUTLINE`.`SECTION` (`CourseID` , `SectionNumber`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
       DROP TABLE if Exists TUTORIAL;
    CREATE TABLE `COURSE_OUTLINE`.`TUTORIAL` (
  `CourseID` VARCHAR(45) NOT NULL,
  `TutorialNum` VARCHAR(4) NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Office` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CourseID`, `TutorialNum`),
  CONSTRAINT `TUTORIAL`
    FOREIGN KEY (`CourseID` , `TutorialNum`)
    REFERENCES `COURSE_OUTLINE`.`SECTION` (`CourseID` , `SectionNumber`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);
    
DROP TABLE if Exists TIMETABLE;
CREATE TABLE `COURSE_OUTLINE`.`TIMETABLE` (
  `CourseID` VARCHAR(45) NOT NULL,
  `SectionNum` VARCHAR(4) NOT NULL,
  `Days` VARCHAR(45) NULL,
  `Time` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`CourseID`,`SectionNum`),

  CONSTRAINT `TIMETABLE`
    FOREIGN KEY (`CourseID` , `SectionNum`)
    REFERENCES `COURSE_OUTLINE`.`SECTION` (`CourseID` , `SectionNumber`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE);







